//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zmblog.Web.xinxianshi {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblxinxianshiID;
	protected global::System.Web.UI.WebControls.Label lbluserID;
	protected global::System.Web.UI.WebControls.Label lblpostTime;
	protected global::System.Web.UI.WebControls.Label lblcommentTitle;
	protected global::System.Web.UI.WebControls.Label lblcommentMsg;
	protected global::System.Web.UI.WebControls.Label lblimgUrl;
	protected global::System.Web.UI.WebControls.Label lblfaceID;
	protected global::System.Web.UI.WebControls.Label lblxinqingID;


       
    }
}
